// Original dashboard with synthetic API fixtures; no provider or live data is used.
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import http from 'node:http';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const {chromium}=await import(process.env.PB_PLAYWRIGHT_MODULE||'playwright');
const source=path.dirname(fileURLToPath(import.meta.url));
const key='HOME_DRILLDOWN_FIXTURE_ONLY',errors=[],writes=[],external=[];
const date=days=>{const d=new Date();d.setDate(d.getDate()+days);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const project=(name,lead)=>({name,lead,health:'Green',stage:'Build',goal:'Fixture project',repo:''});
const projects=[project('Alpha','Ann'),project('Beta','Bob'),project('Gamma','Ann'),project('Delta',''),project('Epsilon',null)];
const task=(id,status,priority='Medium',owner='Ann',project='Alpha',due_date='')=>({id,title:`Fixture ${id}`,status,priority,owner,project,due_date,executor:'human',note:'Fixture only',progress:0,updated_at:Date.now()/1000});
const tasks=[task('open','Backlog'),task('active','Active','High','Ann','Alpha',date(0)),task('blocked','Blocked','Critical','Bob','Alpha',date(7)),task('done','Done','Critical','Ann','Alpha',date(0)),task('overdue','Active','Low','Bob','Alpha',date(-1)),task('future','Review','Critical','Cara','Alpha',date(8)),task('other','Active','Critical','Bob','Beta',date(1)),task('running-old','Active','Medium','Cara'),task('queued','Backlog')];
tasks.find(t=>t.id==='blocked').title='Fixture blocked <img src=x onerror="window.HOME_XSS=true">';
tasks.find(t=>t.id==='running-old').last_run_id='finished-latest';tasks.find(t=>t.id==='queued').last_run_id='queued-run';
const runs=[{id:'running-one',task_id:'running-old',project:'Alpha',agent_key:'builder',status:'running',issue_number:1},{id:'running-two',task_id:'running-old',project:'Alpha',agent_key:'verifier',status:'running',issue_number:2},{id:'finished-latest',task_id:'running-old',project:'Alpha',agent_key:'builder',status:'completed',issue_number:3},{id:'queued-run',task_id:'queued',project:'Alpha',agent_key:'builder',status:'queued',issue_number:4}];
const field=(text,format='text',extra={})=>({text,format,source:'fixture',recorded_chars:text.length,truncated:false,redacted:false,...extra});
const observed=(id,kind,evidence,tokens={total:null,input:null,output:null,cache_read:null,cache_write:null})=>({id,session:'fixture-session',kind,tool:kind==='tool_use'?'read':kind,status:'completed',time:Date.now()/1000,duration_ms:kind==='tool_use'?42:null,tokens,evidence,summary:kind==='prompt'?'User prompt: review this fixture':kind==='assistant_message'?'Agent update: review complete':kind==='tool_use'?'Read the fixture file':'Recorded model usage',argument_fields:kind==='tool_use'?['path']:[],error_recorded:false});
const obsEvents=[observed('obs-prompt','prompt',{prompt:field('PROMPT_FIXTURE <img src=x onerror="window.OBS_XSS=true">')}),observed('obs-tool','tool_use',{arguments:field('{"path":"fixture.txt","api_key":"[redacted]"}','json',{redacted:true}),response:field('RESULT_FIXTURE: the file contains the expected record.', 'text',{truncated:true})}),observed('obs-update','assistant_message',{message:field('UPDATE_FIXTURE: the review is complete.')}),observed('obs-tokens','step_finish',null,{total:42,input:30,output:12,cache_read:0,cache_write:2})];
const observation={version:1,observed_at:Date.now()/1000,capabilities:{owner_evidence:true,execution_permissions:false},sources:[{state:'available'}],traces:[{id:'fixture-trace',project:'Alpha',role:'Builder',label:'Fixture run',status:'recorded',events:obsEvents,partial:false,tokens:42}]};
const settings={general:{default_view:'home',show_completed:true,refresh_seconds:60},notifications:{},ai:{},filters:{saved_views:[]}};
let html=(await Promise.all((await fs.readdir(path.join(source,'index'))).filter(n=>n.endsWith('.part')).sort().map(n=>fs.readFile(path.join(source,'index',n),'utf8')))).join('');
const files=new Map();
for(const name of ['home.js','home-inspector.js','health-runtime.js','ai-connections.js','codex-workspace.js']){files.set('/'+name,{body:await fs.readFile(path.join(source,name)),type:'text/javascript'});const tag=`<script src="/${name}"></script>`;if(!html.includes(tag))html=html.replace('</body>',tag+'</body>');}
files.set('/',{body:html,type:'text/html'});
const server=http.createServer(async(req,res)=>{
  const url=new URL(req.url,'http://fixture.local');
  if(files.has(url.pathname)){const f=files.get(url.pathname);res.writeHead(200,{'Content-Type':f.type});res.end(f.body);return;}
  if(!['GET','HEAD'].includes(req.method))writes.push({path:url.pathname,method:req.method});
  const send=data=>{res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify(data));};
  if(url.pathname==='/api/session')return send({ok:true,level:4,role:'owner',name:'Fixture owner',subject:'fixture-owner'});
  if(url.pathname==='/api/tasks')return send({tasks});
  if(url.pathname==='/api/projects')return send({projects});
  if(url.pathname==='/api/runs')return send({runs});
  if(url.pathname==='/api/observatory')return send(observation);
  if(url.pathname==='/api/settings')return send({settings});
  if(url.pathname==='/api/intelligence')return send({top:[],signals:{}});
  if(url.pathname==='/api/workspace-profile')return send({profile:{schema_version:1,display_name:'PRFKT_PROJECT',assistant_name:'AI_BYTE',owner_shortcuts:['Ann','Bob']}});
  if(url.pathname==='/api/ai-connections')return send({providers:[],connections:[],codex:{available:false,connected:false}});
  if(url.pathname==='/api/codex-workspace')return send({configured:false,connected:false,projects:[],conversations:[]});
  if(url.pathname==='/api/execution-permissions')return send({state:'not_connected',requests:[]});
  if(url.pathname==='/healthz')return send({ok:true,version:'fixture',components:{},readiness:{}});
  if(url.pathname.endsWith('/terminal'))return send({lines:['Fixture run output']});
  return send({ok:true,[url.pathname.split('/').pop()]:[],items:[],repositories:{},traces:[],sources:[],version:1});
});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const base=`http://127.0.0.1:${server.address().port}`;
const out=process.env.PB_SCREENSHOTS||await fs.mkdtemp(path.join(os.tmpdir(),'pb-home-drilldown-'));
await fs.mkdir(out,{recursive:true});
let browser;
try{
  browser=await chromium.launch({headless:true,...(process.env.PB_BROWSER_PATH?{executablePath:process.env.PB_BROWSER_PATH}:{})});
  const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
  page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith(base)&&!r.url().startsWith('data:'))external.push(r.url());});
  await page.addInitScript(key=>sessionStorage.setItem('project_byte_access',key),key);
  await page.goto(base,{waitUntil:'networkidle'});await page.waitForSelector('#home.active');
  assert.equal(await page.locator('#home .home-command,#home [data-home-action="ask"]').count(),0,'Home AI entry is removed');
  assert.ok(await page.locator('.home-nav [data-home-go="ai"]').count(),'existing chat dock remains');
  const expected={open:['open','active','blocked','overdue','future','other','running-old','queued'],active:['active','overdue','other','running-old'],blocked:['blocked'],critical:['blocked','future','other'],ai:['running-one','running-two'],due:['active','blocked','other']};
  for(const [kind,ids] of Object.entries(expected)){
    await page.evaluate(()=>clearFilters());
    assert.equal(Number(await page.locator(`[data-home-kpi="${kind}"] b`).textContent()),ids.length);
    await page.locator(`[data-home-kpi="${kind}"]`).click();await page.waitForSelector('#homeKpiDialog[open]');
    const shown=await page.locator('#homeKpiDialog [data-home-record]').evaluateAll(rows=>rows.map(r=>r.dataset.homeRecord).sort());
    assert.deepEqual(shown,[...ids].sort(),`${kind}: exact pre-click counter records, without My work narrowing`);
    assert.equal(await page.locator('#homeKpiDialog img').count(),0,'record labels are escaped');
    assert.ok(await page.locator('#homeKpiDialog [data-home-task]').count()>0,'matching records have task actions');
    await page.locator('[data-home-kpi-close]').click();
  }
  assert.equal(await page.evaluate(()=>!!window.HOME_XSS),false);
  await page.evaluate(()=>{clearFilters();document.getElementById('ownerFilter').value='Bob';document.getElementById('projectFilter').value='Alpha';renderAll();});
  await page.locator('[data-home-kpi="blocked"]').click();
  assert.deepEqual(await page.locator('#homeKpiDialog [data-home-record]').evaluateAll(rows=>rows.map(r=>r.dataset.homeRecord)),['blocked']);
  assert.match(await page.locator('.home-kpi-scope').textContent(),/Project: Alpha.*Owner: Bob/);
  assert.equal(await page.locator('#ownerFilter').inputValue(),'Bob');assert.equal(await page.locator('#projectFilter').inputValue(),'Alpha');
  await page.locator('#homeKpiDialog [data-home-task="blocked"]').click();
  assert.equal(await page.locator('#homeKpiDialog').evaluate(e=>e.open),false);await page.waitForSelector('#taskModal.open');
  assert.equal(await page.locator('#taskId').inputValue(),'blocked');await page.keyboard.press('Escape');
  await page.evaluate(()=>clearFilters());await page.locator('[data-home-kpi="ai"]').click();
  await page.locator('#homeKpiDialog [data-home-run="running-one"]').click();
  await page.waitForSelector('#terminalView.active');assert.equal(await page.locator('#terminalRun').inputValue(),'running-one');
  await page.evaluate(()=>{clearFilters();document.querySelector('[data-view="home"]').click();});
  await page.locator('[data-home-kpi="open"]').click();await page.locator('#homeKpiDialog [data-home-board="Alpha"]').first().click();
  await page.waitForSelector('#board.active');assert.equal(await page.locator('#projectFilter').inputValue(),'Alpha');
  await page.evaluate(()=>{clearFilters();document.querySelector('[data-view="portfolio"]').click();});
  await page.locator('#projects [data-lead="Ann"]').first().click();
  assert.deepEqual(await page.locator('#projects .projecthead h2').allTextContents(),['Alpha','Gamma']);
  assert.match(await page.locator('#pbWorkspaceScope').textContent(),/Lead: Ann/);assert.equal(await page.locator('#pbFilterDialog').evaluate(e=>e.open),false);
  await page.evaluate(()=>{clearFilters();document.getElementById('ownerFilter').value='Bob';renderAll();});
  await page.locator('#projects [data-lead="Ann"]').click();assert.equal(await page.locator('#ownerFilter').inputValue(),'Bob');
  assert.deepEqual(await page.locator('#projects .projecthead h2').allTextContents(),['Alpha']);
  await page.evaluate(()=>clearFilters());await page.locator('#projects [data-lead=""]').first().click();
  assert.deepEqual(await page.locator('#projects .projecthead h2').allTextContents(),['Delta','Epsilon']);
  assert.match(await page.locator('#pbWorkspaceScope').textContent(),/Lead: Unassigned/);
  await page.evaluate(()=>{syncSelectors();renderAll();});
  assert.deepEqual(await page.locator('#projects .projecthead h2').allTextContents(),['Delta','Epsilon'],'unassigned lead survives data selector refresh');
  await page.evaluate(()=>{clearFilters();document.getElementById('ownerFilter').value='Ann';document.getElementById('statusFilter').value='Blocked';renderAll();document.querySelector('[data-view="home"]').click();});
  await page.locator('[data-home-kpi="blocked"]').click();assert.equal(await page.locator('#homeKpiDialog [data-home-record]').count(),0);
  assert.match(await page.locator('#homeKpiDialog').innerText(),/No matching records/);await page.keyboard.press('Escape');
  await page.evaluate(()=>clearFilters());
  for(const width of [320,390,1440]){
    await page.setViewportSize({width,height:900});await page.locator('[data-home-kpi="open"]').click();
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`no horizontal page overflow at ${width}`);
    const rect=await page.locator('#homeKpiDialog').boundingBox();assert.ok(rect.x>=0&&rect.x+rect.width<=width+1,'dialog fits viewport');
    await page.screenshot({path:path.join(out,`home-drilldown-${width}.png`),fullPage:true});await page.keyboard.press('Escape');
  }
  await page.evaluate(()=>document.querySelector('[data-view="agents"]').click());
  await page.locator('#obsRefresh').click();await page.waitForSelector('#obsEventFeed [data-obs-event="obs-prompt"]');
  await page.locator('#obsEventFeed [data-obs-event="obs-prompt"]').click();
  assert.match(await page.locator('#obsInspector [data-obs-evidence="prompt"]').innerText(),/PROMPT_FIXTURE <img/);
  assert.equal(await page.locator('#obsInspector img').count(),0,'observed evidence is escaped');assert.equal(await page.evaluate(()=>!!window.OBS_XSS),false);
  await page.locator('#obsInspector [data-obs-open-run]').click();
  await page.locator('#obsEventFeed [data-obs-event="obs-tool"]').click();
  assert.match(await page.locator('#obsInspector [data-obs-evidence="arguments"]').innerText(),/fixture.txt.*[\s\S]*Credentials redacted/);
  assert.match(await page.locator('#obsInspector [data-obs-evidence="response"]').innerText(),/RESULT_FIXTURE[\s\S]*Truncated excerpt/);
  assert.equal(await page.locator('#obsInspector .obs-event-metadata').evaluate(e=>e.open),false,'raw metadata starts collapsed');
  assert.match(await page.locator('#obsInspector dl').innerText(),/Not recorded/,'missing metrics stay unknown');
  await page.context().grantPermissions(['clipboard-read','clipboard-write'],{origin:base});
  await page.locator('#obsInspector [data-obs-copy-field="response"]').click();
  assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),obsEvents[1].evidence.response.text,'copy uses the same bounded evidence');
  await page.locator('#obsInspector [data-obs-open-run]').click();
  await page.locator('#obsEventFeed [data-obs-event="obs-update"]').click();
  assert.match(await page.locator('#obsInspector [data-obs-evidence="message"]').innerText(),/UPDATE_FIXTURE/);
  await page.locator('#obsInspector [data-obs-open-run]').click();
  await page.locator('#obsEventFeed [data-obs-event="obs-tokens"]').click();
  assert.match(await page.locator('#obsInspector dl').innerText(),/Tokens\s+42/);assert.match(await page.locator('#obsInspector dl').innerText(),/Cache read\s+0/);
  for(const width of [390,1440]){await page.setViewportSize({width,height:1000});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'readable evidence fits viewport');await page.screenshot({path:path.join(out,`observatory-readable-${width}.png`),fullPage:false});}
  console.log('OBSERVATORY_READABLE_PROMPT_UPDATE_ARGUMENTS_RESULT_METRICS=PASS');
  assert.equal(writes.length,0,'counter, lead, editor and navigation actions do not mutate records or queue work: '+JSON.stringify(writes));
  assert.equal(errors.length,0,'no browser exceptions: '+errors.join('; '));assert.equal(external.length,0,'no external requests');
  console.log('HOME_EXACT_COUNTER_RECORDS_AND_ACTIONS=PASS');console.log('PROJECT_LEAD_AND_UNASSIGNED_SCOPE=PASS');console.log('NO_MUTATIONS_OR_AUTOQUEUE=PASS');console.log('SCREENSHOTS='+out);
}catch(error){console.error(error);process.exitCode=1;}finally{if(browser)await browser.close();await new Promise(resolve=>server.close(resolve));}
