import assert from 'node:assert/strict';
import path from 'node:path';
export async function verifyLiveUpdates({browser,api,base,out,key}){
 const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),page=await context.newPage(),errors=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept(d.type()==='prompt'?key:undefined));
 await page.goto(base,{waitUntil:'domcontentloaded'});await page.locator('#login').click();
 await page.waitForFunction(()=>session.ok&&document.querySelector('#prfktUpdatesButton')?.dataset.state==='connected');
 await page.waitForTimeout(1000);
 assert.equal(await page.locator('.prfkt-update-card').count(),0,'no historical popup flood at sign-in');
 await page.evaluate(()=>{openTask();document.querySelector('#taskTitle').value='Keep my unsaved draft';document.querySelector('#taskTitle').focus();});
 const created=await api('/api/tasks','POST',{title:'Incoming real-time fixture',project:'Live QA',status:'Backlog',owner:'Joe'});
 await page.evaluate(()=>refreshWorkspace());
 await page.waitForFunction(()=>tasks.some(t=>t.title==='Incoming real-time fixture'));
 await page.waitForTimeout(200);assert.equal(await page.locator('.prfkt-update-card').count(),0,'routine task creation does not interrupt');
 await page.evaluate(()=>window.dispatchEvent(new CustomEvent('prfkt-live-event',{detail:{id:'fixture:important',title:'Error requires attention',message:'Incoming real-time fixture',source:'Notification'}})));
 await page.waitForSelector('.prfkt-update-card');
 assert.equal(await page.locator('#taskTitle').inputValue(),'Keep my unsaved draft','updates do not overwrite active form');
 await page.evaluate(()=>closeModal('taskModal'));
 await page.locator('.prfkt-update-card>button:first-child').first().click();
 await page.waitForSelector('#prfktUpdates[open]');assert.match(await page.locator('#prfktUpdateDetail').textContent(),/Incoming real-time fixture/);
 await page.screenshot({path:path.join(out,'detail-desktop.png')});await page.locator('#prfktUpdateClose').click();
 // Visible agent payload is rendered as text, saved encrypted, and fades without being lost.
 await page.evaluate(()=>window.dispatchEvent(new CustomEvent('prfkt-live-event',{detail:{id:'fixture:agent',title:'AI_BYTE update',message:'Building safely <img src=x onerror="window.BAD=true">',source:'Agent',link:'#ai'}})));
 await page.waitForSelector('[data-event-id="fixture:agent"]');
 assert.equal(await page.locator('[data-event-id="fixture:agent"] img').count(),0);
 await page.waitForTimeout(8800);assert.equal(await page.locator('[data-event-id="fixture:agent"]').count(),0,'popup fades away');
 const stored=await page.evaluate(()=>Object.entries(localStorage).filter(([k])=>k.startsWith('prfkt.updates.v1.')));
 assert.ok(stored.length);assert.ok(stored.every(([,v])=>!v.includes('Building safely')),'history is not plaintext');
 await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>session.ok&&document.querySelector('#prfktUpdatesButton')?.dataset.state==='connected');
 await page.locator('#prfktUpdatesButton').click();await page.locator('[data-update-id="fixture:agent"]').click();
 assert.match(await page.locator('#prfktUpdateDetail').textContent(),/Building safely <img/,'missed popup survives reload');
 await page.locator('#prfktUpdateClose').click();
 await page.route('**/api/tasks',route=>route.abort());await page.evaluate(()=>refreshWorkspace());
 await page.waitForFunction(()=>document.querySelector('#prfktUpdatesButton').title.includes('interrupted'));
 await page.unroute('**/api/tasks');await page.evaluate(()=>window.dispatchEvent(new Event('online')));
 await page.waitForFunction(()=>document.querySelector('#prfktUpdatesButton').dataset.state==='connected');
 await page.setViewportSize({width:320,height:740});await page.locator('#prfktUpdatesButton').click();
 let box=await page.locator('#prfktUpdates').boundingBox();assert.ok(box.x>=0&&box.x+box.width<=321&&box.y>=0&&box.y+box.height<=741,'drawer fits phone');
 await page.screenshot({path:path.join(out,'history-mobile.png')});await page.locator('#prfktUpdateClose').click();
 await page.locator('#prfktUpdatesButton').click();await page.locator('#prfktUpdatePopups').uncheck();await page.locator('#prfktUpdateClose').click();
 await page.evaluate(()=>window.dispatchEvent(new CustomEvent('prfkt-live-event',{detail:{id:'fixture:muted',title:'Muted but saved',message:'An observed update',source:'Activity'}})));
 await page.waitForTimeout(500);assert.equal(await page.locator('.prfkt-update-card').count(),0);
 await page.locator('#prfktUpdatesButton').click();await page.locator('[data-update-id="fixture:muted"]').waitFor();await page.locator('#prfktUpdateReadAll').click();assert.match(await page.locator('#prfktUpdatesButton').getAttribute('aria-label'),/0 unread/);await page.locator('#prfktUpdateClose').click();
 await page.locator('#login').click();await page.waitForFunction(()=>!session.ok);
 assert.equal(await page.locator('#prfktUpdatesButton').isVisible(),false);assert.equal(await page.locator('#prfktUpdateList').textContent(),'');assert.equal(await page.locator('.prfkt-update-card').count(),0);
 const viewer=await api('/api/team','POST',{name:'Live updates viewer '+Date.now(),role:'viewer'});
 await page.evaluate(k=>sessionStorage.setItem('project_byte_access',k),viewer.access_key);await page.reload({waitUntil:'domcontentloaded'});
 await page.waitForFunction(()=>session.ok&&session.role==='viewer'&&document.querySelector('#prfktUpdatesButton').dataset.state==='connected');
 await page.locator('#prfktUpdatesButton').click();assert.equal(await page.locator('[data-update-id="fixture:agent"]').count(),0,'another account cannot load owner agent history');
 assert.ok(!(await page.locator('#prfktUpdateList').textContent()).includes('Building safely'));
 assert.deepEqual(errors,[]);await context.close();console.log('PASS live updates: real API arrival during editing, popup detail/fade, encrypted reload history, offline recovery, mobile bounds, mute/history, sign-out privacy, escaped model text');
}
