import os
import sqlite3
import tempfile
import time
import unittest
from pathlib import Path

import joeos_backend as backend
from server.engineering.service import EngineeringService
from server.intelligence import IntelligenceService
from server.intelligence.parser import parse, supported_languages


def _wait_until(service, project_id, timeout=30.0):
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        if not service.is_indexing(project_id):
            return service.index_health(project_id)
        time.sleep(0.05)
    return service.index_health(project_id)


class IntelligenceFixture(unittest.TestCase):
    def setUp(self):
        self.tempdir = tempfile.TemporaryDirectory()
        self.project_root = Path(self.tempdir.name) / "sample-project"
        self.project_root.mkdir()
        (self.project_root / "src").mkdir()
        (self.project_root / "tests").mkdir()
        (self.project_root / "docs").mkdir()
        (self.project_root / "docs" / "adr").mkdir()
        (self.project_root / "src" / "app.py").write_text(
            "import os\nfrom src import utils\n\n"
            "class App:\n    def run(self):\n        return utils.helper()\n"
        )
        (self.project_root / "src" / "utils.py").write_text(
            "def helper():\n    return 42\n"
        )
        (self.project_root / "tests" / "test_app.py").write_text(
            "import pytest\nfrom src.app import App\n\n"
            "def test_run():\n    assert App().run() == 42\n"
        )
        (self.project_root / "docs" / "adr" / "0001-decide.md").write_text(
            "# 0001 Use FastAPI\n\n* Status: accepted\n* Date: 2026-01-01\n\n"
            "Use FastAPI for the backend.\n"
        )
        (self.project_root / ".prettierrc").write_text('{\n  "semi": false,\n  "tabWidth": 2\n}')
        (self.project_root / ".env").write_text("SECRET_KEY=super-secret\n")
        (self.project_root / "README.md").write_text("# Sample Project\n\n## Overview\n")
        self.db_path = str(Path(self.tempdir.name) / "joeos.db")
        self.engineering = EngineeringService(lambda: backend._connect(self.db_path))
        self.project = self.engineering.register_project("sample", str(self.project_root))
        self.service = IntelligenceService(
            self.engineering.projects,
            str(Path(self.tempdir.name) / "intel"),
        )

    def tearDown(self):
        self.tempdir.cleanup()


class IdentityTests(IntelligenceFixture):
    def test_identity_detects_languages_and_fingerprint_is_stable(self):
        identity = self.service.identity_for(self.project.project_id)
        self.assertIn("python", identity.languages)
        self.assertEqual(identity.name, "sample-project")
        self.assertTrue(len(identity.fingerprint) >= 8)

        fingerprint = self.service.fingerprint_for(self.project.project_id)
        self.assertEqual(fingerprint.fingerprint, identity.fingerprint)

    def test_fingerprint_remains_stable_across_branch_switch(self):
        first = self.service.fingerprint_for(self.project.project_id)
        second = self.service.fingerprint_for(self.project.project_id)
        self.assertEqual(first.fingerprint, second.fingerprint)
        stable = [c for c in second.components if c.stable_across_branches]
        self.assertTrue(stable)
        self.assertTrue(any(c.name == "name" for c in stable))

    def test_unknown_project_raises(self):
        from server.engineering.projects import ProjectNotFoundError

        with self.assertRaises(ProjectNotFoundError):
            self.service.identity_for("does-not-exist")


class InventoryTests(IntelligenceFixture):
    def test_classification_and_secret_exclusion(self):
        records = {r.rel_path: r for r in self.service.file_inventory(self.project.project_id)}
        self.assertIn("src/app.py", records)
        self.assertEqual(records["src/app.py"].classification, "source")
        self.assertTrue(records[".env"].secret_sensitive)
        self.assertIn("tests/test_app.py", records)
        self.assertEqual(records["tests/test_app.py"].classification, "test")
        self.assertTrue(records["README.md"].classification in {"documentation"})

    def test_content_hash_is_sha256(self):
        records = {r.rel_path: r for r in self.service.file_inventory(self.project.project_id)}
        self.assertEqual(len(records["src/app.py"].content_hash), 64)

    def test_generated_flag_only_from_header_marker(self):
        from server.intelligence.inventory import _policy_flags

        self.assertTrue(_policy_flags("src/gen.py", b"# do not edit\nx = 1\n", 16)[0])
        self.assertFalse(_policy_flags("src/gen.py", b"value = 'generated by default'\nx = 1\n", 40)[0])
        self.assertFalse(_policy_flags("src/gen.py", b"SELECT 1 -- generated by default\n", 34)[0])


class ParserTests(IntelligenceFixture):
    def test_python_symbols_and_imports(self):
        content = (self.project_root / "src" / "app.py").read_text()
        result = parse(content, "python", "p", "f" * 24, "src/app.py")
        names = [s.name for s in result.symbols]
        self.assertIn("App", names)
        self.assertIn("run", names)
        imports = {r.target_text for r in result.references}
        self.assertIn("os", imports)
        self.assertIn("src", imports)

    def test_parser_errors_are_isolated(self):
        result = parse("def broken(:", "python", "p", "f" * 24, "broken.py")
        self.assertIsNotNone(result.symbols)
        self.assertIsNotNone(result.references)

    def test_unsupported_language_returns_no_parser(self):
        result = parse("content", "prolog", "p", "f" * 24, "x.pl")
        self.assertEqual(result.error, "no_parser")

    def test_supported_languages_are_exposed(self):
        self.assertIn("python", supported_languages())
        self.assertIn("markdown", supported_languages())


class IndexLifecycleTests(IntelligenceFixture):
    def test_full_index_reaches_healthy(self):
        self.service.trigger_full_index(self.project.project_id)
        health = _wait_until(self.service, self.project.project_id)
        self.assertEqual(health.phase, "completed")
        self.assertIn(health.state, {"healthy", "degraded"})
        self.assertGreaterEqual(health.diagnostics.indexed_files, 5)
        self.assertGreater(health.diagnostics.symbols, 0)

    def test_incremental_index_after_change(self):
        self.service.trigger_full_index(self.project.project_id)
        _wait_until(self.service, self.project.project_id)
        full_time = self.service.index_health(self.project.project_id).diagnostics.last_full_index
        self.assertTrue(full_time)
        self.project_root.joinpath("src", "app.py").write_text(
            "import os\nfrom src import utils\n\n"
            "class App:\n    def run(self):\n        return utils.helper() + 1\n"
        )
        self.service.trigger_incremental_index(self.project.project_id)
        health = _wait_until(self.service, self.project.project_id)
        self.assertEqual(health.phase, "completed")
        self.assertIn(health.state, {"healthy", "degraded"})
        self.assertEqual(health.diagnostics.last_full_index, full_time)
        self.assertTrue(health.diagnostics.last_incremental_update)

    def test_cancel_marks_cancelled(self):
        self.service.trigger_full_index(self.project.project_id)
        deadline = time.monotonic() + 10
        while time.monotonic() < deadline and not self.service.is_indexing(self.project.project_id):
            time.sleep(0.01)
        self.service.cancel_index(self.project.project_id)
        deadline = time.monotonic() + 10
        while time.monotonic() < deadline and self.service.is_indexing(self.project.project_id):
            time.sleep(0.01)
        health = self.service.index_health(self.project.project_id)
        self.assertIn(health.state, {"cancelled", "healthy", "degraded"})

    def test_index_health_contract_fields(self):
        health = self.service.index_health(self.project.project_id)
        self.assertIsInstance(health.diagnostics, object)
        self.assertTrue(health.updated_at)


class DependencyGraphTests(IntelligenceFixture):
    def test_graph_resolves_and_reports_externals(self):
        self.service.trigger_full_index(self.project.project_id)
        _wait_until(self.service, self.project.project_id)
        graph = self.service.dependency_graph(self.project.project_id)
        by_source = {e.source_rel_path: e for e in graph.edges}
        self.assertIn("tests/test_app.py", by_source)
        self.assertEqual(by_source["tests/test_app.py"].target_rel_path, "src/app.py")
        self.assertIn("os", graph.external_dependencies)

    def test_architecture_graph_evidence_only(self):
        self.service.trigger_full_index(self.project.project_id)
        _wait_until(self.service, self.project.project_id)
        arch = self.service.architecture_graph(self.project.project_id)
        self.assertTrue(all(n.derived_from == "evidence" for n in arch.nodes))


class ChangeImpactTests(IntelligenceFixture):
    def test_change_impact_uses_likelihood_not_certainty(self):
        self.service.trigger_full_index(self.project.project_id)
        _wait_until(self.service, self.project.project_id)
        impacts = self.service.change_impact(self.project.project_id, "src/app.py")
        paths = [i.impacted_path for i in impacts]
        self.assertIn("tests/test_app.py", paths)
        for item in impacts:
            self.assertIn(item.likelihood, {"direct", "likely", "possible", "insufficient_evidence"})

    def test_unknown_target_yields_no_impact(self):
        self.service.trigger_full_index(self.project.project_id)
        _wait_until(self.service, self.project.project_id)
        impacts = self.service.change_impact(self.project.project_id, "nope/nowhere.py")
        self.assertEqual(impacts, ())


class RiskTests(IntelligenceFixture):
    def test_risk_findings_are_explainable(self):
        self.service.trigger_full_index(self.project.project_id)
        _wait_until(self.service, self.project.project_id)
        findings = self.service.risk_findings(self.project.project_id)
        categories = {f.category for f in findings}
        self.assertIn("unresolved_references", categories)
        for finding in findings:
            self.assertTrue(finding.evidence)


class KnowledgeTests(IntelligenceFixture):
    def test_adr_ingested_from_docs(self):
        self.service.trigger_full_index(self.project.project_id)
        _wait_until(self.service, self.project.project_id)
        decisions = self.service.decisions(self.project.project_id)
        self.assertTrue(any("FastAPI" in d.title for d in decisions))

    def test_conventions_detected_from_prettier(self):
        self.service.trigger_full_index(self.project.project_id)
        _wait_until(self.service, self.project.project_id)
        conventions = self.service.conventions(self.project.project_id)
        self.assertTrue(any("semi" in c.convention for c in conventions))

    def test_memory_round_trip(self):
        from server.intelligence.models import MemoryEntry, Provenance

        now = "2026-01-01T00:00:00+00:00"
        entry = MemoryEntry(
            memory_id="m" + "a" * 23,
            project_id=self.project.project_id,
            summary="Remember to keep the index local-first.",
            status="proposed",
            confidence="reported",
            source=Provenance(kind="user", source="operator", detected_at=now),
            created_at=now,
            updated_at=now,
        )
        saved = self.service.add_memory(self.project.project_id, entry)
        self.assertEqual(saved.summary, entry.summary)
        ok = self.service.update_memory(self.project.project_id, saved.memory_id, "accepted")
        self.assertTrue(ok)
        memories = self.service.memories(self.project.project_id)
        self.assertEqual(len(memories), 1)
        self.assertEqual(memories[0].status, "accepted")


class RetrievalTests(IntelligenceFixture):
    def test_search_returns_ranked_results(self):
        self.service.trigger_full_index(self.project.project_id)
        _wait_until(self.service, self.project.project_id)
        envelope = self.service.search(self.project.project_id, "app")
        self.assertTrue(envelope.hybrid)
        self.assertTrue(envelope.results)
        self.assertLessEqual(len(envelope.results), 25)
        scores = [r.score for r in envelope.results]
        self.assertEqual(scores, sorted(scores, reverse=True))

    def test_context_pack_builds_items_with_reasons(self):
        self.service.trigger_full_index(self.project.project_id)
        _wait_until(self.service, self.project.project_id)
        pack = self.service.context_pack(self.project.project_id, "understand app", ("src/app.py",))
        self.assertEqual(pack.objective, "understand app")
        self.assertTrue(pack.items)
        self.assertTrue(all(i.reason for i in pack.items))


class StorageTests(IntelligenceFixture):
    def test_storage_stats(self):
        stats = self.service.storage_stats(self.project.project_id)
        self.assertEqual(stats["version"], 1)
        self.assertTrue(stats["path"].endswith("intelligence.db"))


class GitHistoryTests(IntelligenceFixture):
    def test_history_parses_commits_and_numstat(self):
        import subprocess

        git = subprocess.run(["git", "--version"], capture_output=True, text=True)
        if git.returncode != 0:
            self.skipTest("git not available")
        subprocess.run(["git", "-C", str(self.project_root), "init", "-b", "main"], check=True, capture_output=True)
        subprocess.run(["git", "-C", str(self.project_root), "config", "user.name", "Test"], check=True, capture_output=True)
        subprocess.run(["git", "-C", str(self.project_root), "config", "user.email", "test@example.com"], check=True, capture_output=True)
        subprocess.run(["git", "-C", str(self.project_root), "add", "."], check=True, capture_output=True)
        subprocess.run(["git", "-C", str(self.project_root), "commit", "-m", "initial"], check=True, capture_output=True)
        (self.project_root / "src" / "app.py").write_text(
            "import os\nfrom src import utils\n\nclass App:\n    def run(self):\n        return utils.helper() + 1\n"
        )
        subprocess.run(["git", "-C", str(self.project_root), "add", "."], check=True, capture_output=True)
        subprocess.run(["git", "-C", str(self.project_root), "commit", "-m", "change app"], check=True, capture_output=True)
        from server.intelligence.gitintel import GitIntelligenceService

        collected = GitIntelligenceService().collect(self.project.project_id, str(self.project_root))
        self.assertEqual(collected.history_depth, 2)
        self.assertTrue(collected.stats)
        by_path = {s.rel_path: s for s in collected.stats}
        self.assertIn("src/app.py", by_path)
        self.assertEqual(by_path["src/app.py"].authors, 1)
        self.assertTrue(collected.ownership)
        self.assertTrue(all(o.kind in {"recent_contributor", "unowned"} for o in collected.ownership))


class ProvenanceTests(unittest.TestCase):
    def test_fingerprint_components_carry_provenance(self):
        from pathlib import Path
        import tempfile

        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            (root / "a.py").write_text("x = 1\n")
            db_path = str(root / "main.db")
            engineering = EngineeringService(lambda: backend._connect(db_path))
            project = engineering.register_project("prov", str(root))
            service = IntelligenceService(
                engineering.projects,
                str(root / "intel"),
            )
            fingerprint = service.fingerprint_for(project.project_id)
            self.assertTrue(fingerprint.components)
            self.assertTrue(all(c.provenance.kind for c in fingerprint.components))
            self.assertEqual(fingerprint.schema_version, 1)


if __name__ == "__main__":
    unittest.main()
