from __future__ import annotations

from datetime import datetime, timezone
from typing import Callable, Optional

from .models import (
    BootstrapDocument,
    CapabilityDescriptor,
    DeviceEnrollmentProfile,
    RouteDescriptor,
    SecurityPosture,
    ServerIdentity,
)
from .repository import SQLiteServerIdentityRepository

DEFAULT_SERVER_VERSION = "2.0.0"


class BootstrapService:
    """Composes the strict, non-secret bootstrap discovery document."""

    def __init__(
        self,
        repository: SQLiteServerIdentityRepository,
        *,
        server_version: str = DEFAULT_SERVER_VERSION,
        now_provider: Optional[Callable[[], datetime]] = None,
    ) -> None:
        self._repository = repository
        self._server_version = server_version
        self._now = now_provider or (lambda: datetime.now(timezone.utc))

    def prepare(self) -> None:
        self._repository.prepare()

    def discover(self) -> BootstrapDocument:
        server_id = self._repository.get_or_create_server_id()
        now = self._now().astimezone(timezone.utc)
        return BootstrapDocument(
            generated_at=now.strftime("%Y-%m-%dT%H:%M:%SZ"),
            server=ServerIdentity(
                server_id=server_id,
                server_version=self._server_version,
            ),
            security=self._security_posture(),
            device_enrollment=DeviceEnrollmentProfile(),
            capabilities=self._capabilities(),
            routes=self._routes(),
        )

    def _security_posture(self) -> SecurityPosture:
        return SecurityPosture(
            warning=(
                "JoeOS is operator-managed and not public-internet ready: no browser-facing "
                "authentication or role-based access is enabled, and no secrets are returned. "
                "Expose only over a private trusted network."
            )
        )

    def _routes(self) -> list[RouteDescriptor]:
        return [
            RouteDescriptor(
                id="bootstrap.discovery",
                path="/api/v1/bootstrap",
                protocol="http",
                methods=("GET",),
                access="read_only",
                description="Non-secret identity and capability discovery.",
            ),
            RouteDescriptor(
                id="workspace.retrieve",
                path="/api/v1/workspace",
                protocol="http",
                methods=("GET",),
                access="read_only",
                description="Read the persistent workspace configuration.",
            ),
            RouteDescriptor(
                id="workspace.configure",
                path="/api/v1/workspace",
                protocol="http",
                methods=("PUT", "PATCH"),
                access="configuration",
                description="Persist workspace and layout configuration with revision checks.",
            ),
            RouteDescriptor(
                id="workspace.guide",
                path="/api/v1/workspace/guide",
                protocol="http",
                methods=("GET",),
                access="read_only",
                description="Workspace configuration guide.",
            ),
            RouteDescriptor(
                id="events.stream",
                path="/ws/events",
                protocol="websocket",
                methods=("WEBSOCKET",),
                access="stream",
                description="Resumable audit-event and telemetry stream.",
            ),
            RouteDescriptor(
                id="telemetry.sample",
                path="/api/v1/telemetry",
                protocol="http",
                methods=("GET",),
                access="read_only",
                description="Bounded host telemetry sample.",
            ),
            RouteDescriptor(
                id="command_center.overview",
                path="/api/v1/command-center/overview",
                protocol="http",
                methods=("GET",),
                access="read_only",
                description="Executive overview aggregated from live subsystem health.",
            ),
            RouteDescriptor(
                id="command_center.services",
                path="/api/v1/command-center/services",
                protocol="http",
                methods=("GET",),
                access="read_only",
                description="Typed service-health contract for registered JoeOS services.",
            ),
            RouteDescriptor(
                id="command_center.activity",
                path="/api/v1/command-center/activity",
                protocol="http",
                methods=("GET",),
                access="read_only",
                description="Filterable, paginated activity timeline.",
            ),
            RouteDescriptor(
                id="engineering.projects.list",
                path="/api/v1/engineering/projects",
                protocol="http",
                methods=("GET", "POST"),
                access="read_write",
                description="Project registry listing and registration.",
            ),
            RouteDescriptor(
                id="engineering.projects.manage",
                path="/api/v1/engineering/projects/{project_id}",
                protocol="http",
                methods=("GET", "DELETE"),
                access="read_write",
                description="Project detail and removal (files preserved).",
            ),
            RouteDescriptor(
                id="engineering.projects.trust",
                path="/api/v1/engineering/projects/{project_id}/trust",
                protocol="http",
                methods=("PUT",),
                access="approval",
                description="Set project trust state for command gating.",
            ),
            RouteDescriptor(
                id="engineering.files",
                path="/api/v1/engineering/projects/{project_id}/files",
                protocol="http",
                methods=("GET",),
                access="read_only",
                description="Project directory listing within root bounds.",
            ),
            RouteDescriptor(
                id="engineering.files.content",
                path="/api/v1/engineering/projects/{project_id}/files/content",
                protocol="http",
                methods=("GET", "PUT"),
                access="read_write",
                description="Read (secret-masked) and conflict-checked edit of files.",
            ),
            RouteDescriptor(
                id="engineering.git.status",
                path="/api/v1/engineering/projects/{project_id}/git",
                protocol="http",
                methods=("GET",),
                access="read_only",
                description="Git branch, staged, unstaged, untracked, conflict state.",
            ),
            RouteDescriptor(
                id="engineering.git.diff",
                path="/api/v1/engineering/projects/{project_id}/git/diff",
                protocol="http",
                methods=("GET",),
                access="read_only",
                description="Parsed, bounded diff hunks.",
            ),
            RouteDescriptor(
                id="engineering.git.stage",
                path="/api/v1/engineering/projects/{project_id}/git/stage",
                protocol="http",
                methods=("POST",),
                access="approval",
                description="Stage paths in the project repository.",
            ),
            RouteDescriptor(
                id="engineering.git.unstage",
                path="/api/v1/engineering/projects/{project_id}/git/unstage",
                protocol="http",
                methods=("POST",),
                access="approval",
                description="Unstage paths in the project repository.",
            ),
            RouteDescriptor(
                id="engineering.git.commit",
                path="/api/v1/engineering/projects/{project_id}/git/commit",
                protocol="http",
                methods=("POST",),
                access="approval",
                description="Commit staged changes with explicit approval and secret screening.",
            ),
            RouteDescriptor(
                id="engineering.secrets.scan",
                path="/api/v1/engineering/projects/{project_id}/secrets",
                protocol="http",
                methods=("GET",),
                access="read_only",
                description="Bounded secret scan of the project tree.",
            ),
            RouteDescriptor(
                id="engineering.secrets.policy",
                path="/api/v1/engineering/secrets/policy",
                protocol="http",
                methods=("GET",),
                access="read_only",
                description="Secret protection policy and masking categories.",
            ),
            RouteDescriptor(
                id="engineering.commands.validate",
                path="/api/v1/engineering/projects/{project_id}/commands/validate",
                protocol="http",
                methods=("POST",),
                access="read_only",
                description="Validate a command against trust, risk, and approval policy.",
            ),
            RouteDescriptor(
                id="engineering.commands.execute",
                path="/api/v1/engineering/projects/{project_id}/commands/execute",
                protocol="http",
                methods=("POST",),
                access="approval",
                description="Execute an approved, bounded command in the project root.",
            ),
            RouteDescriptor(
                id="engineering.search",
                path="/api/v1/engineering/projects/{project_id}/search",
                protocol="http",
                methods=("GET",),
                access="read_only",
                description="Bounded repository search that excludes secret-bearing files.",
            ),
            RouteDescriptor(
                id="engineering.activity",
                path="/api/v1/engineering/projects/{project_id}/activity",
                protocol="http",
                methods=("GET",),
                access="read_only",
                description="Per-project engineering activity log.",
            ),
            RouteDescriptor(
                id="intelligence.identity",
                path="/api/v1/intelligence/projects/{project_id}/identity",
                protocol="http",
                methods=("GET",),
                access="read_only",
                description="Project identity and language/framework detection.",
            ),
            RouteDescriptor(
                id="intelligence.fingerprint",
                path="/api/v1/intelligence/projects/{project_id}/fingerprint",
                protocol="http",
                methods=("GET",),
                access="read_only",
                description="Stable repository fingerprint with provenance components.",
            ),
            RouteDescriptor(
                id="intelligence.overview",
                path="/api/v1/intelligence/projects/{project_id}/overview",
                protocol="http",
                methods=("GET",),
                access="read_only",
                description="Aggregated project intelligence overview.",
            ),
            RouteDescriptor(
                id="intelligence.files",
                path="/api/v1/intelligence/projects/{project_id}/files",
                protocol="http",
                methods=("GET",),
                access="read_only",
                description="Incremental file inventory with classifications and evidence.",
            ),
            RouteDescriptor(
                id="intelligence.dependencies",
                path="/api/v1/intelligence/projects/{project_id}/dependencies",
                protocol="http",
                methods=("GET",),
                access="read_only",
                description="Dependency graph with cycles and external dependencies.",
            ),
            RouteDescriptor(
                id="intelligence.architecture",
                path="/api/v1/intelligence/projects/{project_id}/architecture",
                protocol="http",
                methods=("GET",),
                access="read_only",
                description="Evidence-based architecture module graph.",
            ),
            RouteDescriptor(
                id="intelligence.git",
                path="/api/v1/intelligence/projects/{project_id}/git",
                protocol="http",
                methods=("GET",),
                access="read_only",
                description="Git history stats, hotspots, and contributor ownership.",
            ),
            RouteDescriptor(
                id="intelligence.impact",
                path="/api/v1/intelligence/projects/{project_id}/impact",
                protocol="http",
                methods=("GET",),
                access="read_only",
                description="Change-impact estimation with likelihood buckets.",
            ),
            RouteDescriptor(
                id="intelligence.risks",
                path="/api/v1/intelligence/projects/{project_id}/risks",
                protocol="http",
                methods=("GET",),
                access="read_only",
                description="Explainable risk findings with cited evidence.",
            ),
            RouteDescriptor(
                id="intelligence.decisions",
                path="/api/v1/intelligence/projects/{project_id}/decisions",
                protocol="http",
                methods=("GET",),
                access="read_only",
                description="Architectural decision records ingested from the project.",
            ),
            RouteDescriptor(
                id="intelligence.conventions",
                path="/api/v1/intelligence/projects/{project_id}/conventions",
                protocol="http",
                methods=("GET",),
                access="read_only",
                description="Detected project conventions with provenance.",
            ),
            RouteDescriptor(
                id="intelligence.memory.list",
                path="/api/v1/intelligence/projects/{project_id}/memory",
                protocol="http",
                methods=("GET",),
                access="read_only",
                description="List project memory entries.",
            ),
            RouteDescriptor(
                id="intelligence.memory.create",
                path="/api/v1/intelligence/projects/{project_id}/memory",
                protocol="http",
                methods=("POST",),
                access="read_write",
                description="Create a project memory entry.",
            ),
            RouteDescriptor(
                id="intelligence.memory.update",
                path="/api/v1/intelligence/projects/{project_id}/memory/{memory_id}/status",
                protocol="http",
                methods=("PUT",),
                access="approval",
                description="Approve or supersede a project memory entry.",
            ),
            RouteDescriptor(
                id="intelligence.search",
                path="/api/v1/intelligence/projects/{project_id}/search",
                protocol="http",
                methods=("GET",),
                access="read_only",
                description="Hybrid structured retrieval over the project index.",
            ),
            RouteDescriptor(
                id="intelligence.context-pack",
                path="/api/v1/intelligence/projects/{project_id}/context-pack",
                protocol="http",
                methods=("POST",),
                access="read_write",
                description="Build a context pack for a stated objective.",
            ),
            RouteDescriptor(
                id="intelligence.index.trigger",
                path="/api/v1/intelligence/projects/{project_id}/index",
                protocol="http",
                methods=("POST",),
                access="read_write",
                description="Trigger a full or incremental background index.",
            ),
            RouteDescriptor(
                id="intelligence.index.cancel",
                path="/api/v1/intelligence/projects/{project_id}/index/cancel",
                protocol="http",
                methods=("POST",),
                access="read_write",
                description="Cancel an in-progress index run.",
            ),
            RouteDescriptor(
                id="intelligence.index.health",
                path="/api/v1/intelligence/projects/{project_id}/index/health",
                protocol="http",
                methods=("GET",),
                access="read_only",
                description="Index health, diagnostics, and freshness state.",
            ),
            RouteDescriptor(
                id="intelligence.index.storage",
                path="/api/v1/intelligence/projects/{project_id}/index/storage",
                protocol="http",
                methods=("GET",),
                access="read_only",
                description="Index storage path and size.",
            ),
            RouteDescriptor(
                id="memory.health",
                path="/api/v1/memory/health",
                protocol="http",
                methods=("GET",),
                access="read_only",
                description="Memory platform health and diagnostics.",
            ),
            RouteDescriptor(
                id="memory.overview",
                path="/api/v1/memory/overview",
                protocol="http",
                methods=("GET",),
                access="read_only",
                description="Memory platform overview with recent records and attention state.",
            ),
            RouteDescriptor(
                id="memory.records.list",
                path="/api/v1/memory/records",
                protocol="http",
                methods=("GET",),
                access="read_only",
                description="List active memory records.",
            ),
            RouteDescriptor(
                id="memory.records.create",
                path="/api/v1/memory/records",
                protocol="http",
                methods=("POST",),
                access="read_write",
                description="Propose a typed memory record with provenance.",
            ),
            RouteDescriptor(
                id="memory.records.manage",
                path="/api/v1/memory/records/{memory_id}",
                protocol="http",
                methods=("GET",),
                access="read_only",
                description="Read a single memory record.",
            ),
            RouteDescriptor(
                id="memory.records.correct",
                path="/api/v1/memory/records/{memory_id}/correct",
                protocol="http",
                methods=("POST",),
                access="approval",
                description="Create a corrected version of a memory record.",
            ),
            RouteDescriptor(
                id="memory.records.supersede",
                path="/api/v1/memory/records/{memory_id}/supersede",
                protocol="http",
                methods=("POST",),
                access="approval",
                description="Supersede a memory record by a replacement.",
            ),
            RouteDescriptor(
                id="memory.records.delete",
                path="/api/v1/memory/records/{memory_id}/delete",
                protocol="http",
                methods=("POST",),
                access="approval",
                description="Soft-delete a memory record with audit.",
            ),
            RouteDescriptor(
                id="memory.records.versions",
                path="/api/v1/memory/records/{memory_id}/versions",
                protocol="http",
                methods=("GET",),
                access="read_only",
                description="Version history for a memory record.",
            ),
            RouteDescriptor(
                id="memory.search",
                path="/api/v1/memory/search",
                protocol="http",
                methods=("GET",),
                access="read_only",
                description="Token-overlap semantic retrieval over memory records.",
            ),
            RouteDescriptor(
                id="memory.review.list",
                path="/api/v1/memory/review",
                protocol="http",
                methods=("GET",),
                access="read_only",
                description="Memory review queue.",
            ),
            RouteDescriptor(
                id="memory.review.resolve",
                path="/api/v1/memory/review/{review_id}",
                protocol="http",
                methods=("POST",),
                access="approval",
                description="Resolve a memory review item.",
            ),
            RouteDescriptor(
                id="memory.entities.list",
                path="/api/v1/memory/entities",
                protocol="http",
                methods=("GET",),
                access="read_only",
                description="List known entities.",
            ),
            RouteDescriptor(
                id="memory.entities.create",
                path="/api/v1/memory/entities",
                protocol="http",
                methods=("POST",),
                access="read_write",
                description="Register an entity.",
            ),
            RouteDescriptor(
                id="memory.relationships.create",
                path="/api/v1/memory/relationships",
                protocol="http",
                methods=("POST",),
                access="read_write",
                description="Register a typed relationship between entities.",
            ),
            RouteDescriptor(
                id="memory.import",
                path="/api/v1/memory/import",
                protocol="http",
                methods=("POST",),
                access="read_write",
                description="Import memory records.",
            ),
            RouteDescriptor(
                id="memory.backup",
                path="/api/v1/memory/backup",
                protocol="http",
                methods=("POST",),
                access="read_write",
                description="Create a storage backup.",
            ),
            RouteDescriptor(
                id="memory.expire",
                path="/api/v1/memory/expire",
                protocol="http",
                methods=("POST",),
                access="read_write",
                description="Expire due memory records.",
            ),
            RouteDescriptor(
                id="memory.storage",
                path="/api/v1/memory/storage",
                protocol="http",
                methods=("GET",),
                access="read_only",
                description="Memory storage path and size.",
            ),
            RouteDescriptor(
                id="health.liveness",
                path="/healthz",
                protocol="http",
                methods=("GET",),
                access="read_only",
                description="Readiness probe without authentication.",
            ),
            RouteDescriptor(
                id="assistant.local_analysis",
                path="/api/chat",
                protocol="http",
                methods=("POST",),
                access="local_analysis",
                description="Read-only local analysis through the private inference runtime.",
            ),
            RouteDescriptor(
                id="device-enrollment.challenge",
                path="/api/v1/device-enrollment/challenges",
                protocol="http",
                methods=("POST",),
                access="enrollment",
                description="Request a device enrollment challenge.",
            ),
            RouteDescriptor(
                id="device-enrollment.complete",
                path="/api/v1/device-enrollment/challenges/{challenge_id}/complete",
                protocol="http",
                methods=("POST",),
                access="enrollment",
                description="Complete device enrollment with a signed proof.",
            ),
        ]

    def _capabilities(self) -> list[CapabilityDescriptor]:
        return [
            CapabilityDescriptor(
                id="discovery.bootstrap",
                status="available",
                access="read_only",
                route_ids=("bootstrap.discovery",),
                description="Non-secret bootstrap discovery.",
            ),
            CapabilityDescriptor(
                id="workspace.read",
                status="available",
                access="read_only",
                route_ids=("workspace.retrieve", "workspace.guide"),
                description="Read workspace configuration.",
            ),
            CapabilityDescriptor(
                id="workspace.configuration",
                status="available",
                access="configuration",
                route_ids=("workspace.configure",),
                description="Persist workspace configuration.",
            ),
            CapabilityDescriptor(
                id="events.streaming",
                status="available",
                access="stream",
                route_ids=("events.stream",),
                description="Resumable audit-event and telemetry stream.",
            ),
            CapabilityDescriptor(
                id="telemetry.monitoring",
                status="available",
                access="read_only",
                route_ids=("telemetry.sample", "health.liveness"),
                description="Bounded local telemetry and liveness.",
            ),
            CapabilityDescriptor(
                id="command_center.overview",
                status="available",
                access="read_only",
                route_ids=(
                    "command_center.overview",
                    "command_center.services",
                    "command_center.activity",
                ),
                description="Executive Command Center aggregation.",
            ),
            CapabilityDescriptor(
                id="engineering.workspace",
                status="available",
                access="read_only",
                route_ids=(
                    "engineering.files",
                    "engineering.git.status",
                    "engineering.git.diff",
                    "engineering.secrets.scan",
                    "engineering.secrets.policy",
                    "engineering.commands.validate",
                    "engineering.search",
                    "engineering.activity",
                ),
                description="Read-only engineering workspace: files, git state, secret scanning, command validation, and search.",
            ),
            CapabilityDescriptor(
                id="engineering.workspace.mutation",
                status="available",
                access="read_write",
                route_ids=(
                    "engineering.projects.list",
                    "engineering.projects.manage",
                    "engineering.files.content",
                ),
                description="Registered-project mutation: register, list, and edit project files with conflict checking.",
            ),
            CapabilityDescriptor(
                id="engineering.workspace.privileged",
                status="available",
                access="approval",
                route_ids=(
                    "engineering.projects.trust",
                    "engineering.git.stage",
                    "engineering.git.unstage",
                    "engineering.git.commit",
                    "engineering.commands.execute",
                ),
                description="Approval-gated engineering operations: trust, git stage/commit, and command execution.",
            ),
            CapabilityDescriptor(
                id="intelligence.project.read",
                status="available",
                access="read_only",
                route_ids=(
                    "intelligence.identity",
                    "intelligence.fingerprint",
                    "intelligence.overview",
                    "intelligence.files",
                    "intelligence.dependencies",
                    "intelligence.architecture",
                    "intelligence.git",
                    "intelligence.impact",
                    "intelligence.risks",
                    "intelligence.index.health",
                    "intelligence.index.storage",
                ),
                description="Read-only project intelligence: identity, inventory, graphs, git stats, impact, risk, and index health.",
            ),
            CapabilityDescriptor(
                id="intelligence.knowledge.read",
                status="available",
                access="read_only",
                route_ids=(
                    "intelligence.decisions",
                    "intelligence.conventions",
                    "intelligence.memory.list",
                    "intelligence.search",
                ),
                description="Read project knowledge: decisions, conventions, memory, and retrieval.",
            ),
            CapabilityDescriptor(
                id="intelligence.knowledge.mutation",
                status="available",
                access="read_write",
                route_ids=(
                    "intelligence.memory.create",
                    "intelligence.context-pack",
                    "intelligence.index.trigger",
                    "intelligence.index.cancel",
                ),
                description="Create memory entries, build context packs, and manage index runs.",
            ),
            CapabilityDescriptor(
                id="intelligence.knowledge.approval",
                status="available",
                access="approval",
                route_ids=("intelligence.memory.update",),
                description="Approval-gated memory status transitions.",
            ),
            CapabilityDescriptor(
                id="memory.knowledge.read",
                status="available",
                access="read_only",
                route_ids=(
                    "memory.health",
                    "memory.overview",
                    "memory.records.list",
                    "memory.records.manage",
                    "memory.records.versions",
                    "memory.search",
                    "memory.review.list",
                    "memory.entities.list",
                    "memory.storage",
                ),
                description="Read the memory platform: records, retrieval, review queue, entities, and storage.",
            ),
            CapabilityDescriptor(
                id="memory.knowledge.mutation",
                status="available",
                access="read_write",
                route_ids=(
                    "memory.records.create",
                    "memory.entities.create",
                    "memory.relationships.create",
                    "memory.import",
                    "memory.backup",
                    "memory.expire",
                ),
                description="Propose records and register entities and relationships.",
            ),
            CapabilityDescriptor(
                id="memory.knowledge.approval",
                status="available",
                access="approval",
                route_ids=(
                    "memory.records.correct",
                    "memory.records.supersede",
                    "memory.records.delete",
                    "memory.review.resolve",
                ),
                description="Approval-gated memory corrections, supersessions, deletions, and review resolution.",
            ),
            CapabilityDescriptor(
                id="assistant.local_analysis",
                status="available",
                access="local_analysis",
                route_ids=("assistant.local_analysis",),
                description="Read-only local analysis.",
            ),
            CapabilityDescriptor(
                id="identity.device_enrollment",
                status="available",
                access="enrollment",
                route_ids=(
                    "device-enrollment.challenge",
                    "device-enrollment.complete",
                ),
                description="Operator pairing without authority.",
            ),
            CapabilityDescriptor(
                id="identity.authentication",
                status="unavailable",
                access="unavailable",
                route_ids=(),
                description="No browser-facing application authentication.",
            ),
            CapabilityDescriptor(
                id="authorization.roles",
                status="unavailable",
                access="unavailable",
                route_ids=(),
                description="No role-based access control.",
            ),
            CapabilityDescriptor(
                id="approvals.privileged_actions",
                status="unavailable",
                access="unavailable",
                route_ids=(),
                description="No privileged-approval workflow.",
            ),
            CapabilityDescriptor(
                id="agents.execution",
                status="unavailable",
                access="unavailable",
                route_ids=(),
                description="No agent execution authority.",
            ),
            CapabilityDescriptor(
                id="secrets.management",
                status="unavailable",
                access="unavailable",
                route_ids=(),
                description="No secret retrieval.",
            ),
        ]
