"""Project and Repository Intelligence platform.

Provides identity, fingerprinting, incremental inventory, classification,
language/framework detection, parser adapters, dependency/architecture graphs,
git intelligence, change-impact analysis, risk findings, decisions/conventions/
memory registries, hybrid retrieval, and an incremental indexing engine.
"""

from .models import (
    ArchitectureGraph,
    ArchitectureNode,
    ChangeHotspot,
    ChangeImpact,
    ClassificationEvidence,
    ContextPack,
    ContextPackItem,
    ConventionRecord,
    DecisionRecord,
    DependencyEdge,
    DependencyGraph,
    FileInventoryRecord,
    FingerprintComponent,
    FrameworkDetection,
    GitHistoryStat,
    GitIntelligence,
    IndexDiagnostics,
    IndexHealth,
    LanguageDetection,
    MemoryEntry,
    OwnershipRecord,
    ProjectIdentity,
    ProjectOverview,
    Provenance,
    ReferenceRecord,
    RepositoryFingerprint,
    RetrievalEnvelope,
    RetrievalResult,
    RiskFinding,
    SymbolRecord,
)
from .router import router as intelligence_router
from .service import IntelligenceService

__all__ = [
    "IntelligenceService",
    "intelligence_router",
    "ArchitectureGraph",
    "ArchitectureNode",
    "ChangeHotspot",
    "ChangeImpact",
    "ClassificationEvidence",
    "ContextPack",
    "ContextPackItem",
    "ConventionRecord",
    "DecisionRecord",
    "DependencyEdge",
    "DependencyGraph",
    "FileInventoryRecord",
    "FingerprintComponent",
    "FrameworkDetection",
    "GitHistoryStat",
    "GitIntelligence",
    "IndexDiagnostics",
    "IndexHealth",
    "LanguageDetection",
    "MemoryEntry",
    "OwnershipRecord",
    "ProjectIdentity",
    "ProjectOverview",
    "Provenance",
    "ReferenceRecord",
    "RepositoryFingerprint",
    "RetrievalEnvelope",
    "RetrievalResult",
    "RiskFinding",
    "SymbolRecord",
]
