"""Authoritative incremental file inventory and evidence-based classification.

The inventory records metadata only (never full contents) and supports lazy
content access through the existing FilesystemService. Classification uses
path evidence, extension evidence, manifest references, and content hints;
folder names alone are never authoritative. Every classification records its
confidence and source.
"""

from __future__ import annotations

import hashlib
import re
from pathlib import Path
from typing import Callable, Dict, List, Optional, Set, Tuple

from .models import FileClassification, FileInventoryRecord, Provenance

GENERATED_HINTS: Tuple[str, ...] = (
    "@generated", "generated by", "code generated", "do not edit", "auto-generated",
    "automatically generated",
)
GENERATED_PATHS: Tuple[str, ...] = (
    "/dist/", "/build/", "/.next/", "/.turbo/", "/.cache/", "/coverage/",
    "/.parcel-cache/", "/out/", "/target/", "/.swiftpm/", "/.pytest_cache/",
    "/.mypy_cache/", "/.ruff_cache/",
)
SECRET_HINTS: Tuple[str, ...] = (
    ".env", "id_rsa", "id_ed25519", ".pem", ".p12", ".pfx", ".keystore",
    ".jks", "service-account.json", "credentials.json", ".secret", "id_dsa",
    "id_ecdsa",
)

TEST_PATH_HINTS = ("/test", "/tests", "/spec", "/specs", "__test__", "test_")
DOCUMENTATION_PATHS = ("/docs/", "/doc/", "/readme", "/changelog", "/adr", "/architecture")
INFRA_PATHS = ("/docker", "/.github/workflows", "/k8s", "/deploy", "/terraform", "/.gitlab-ci")
SCHEMA_PATHS = ("/migrations", "/schemas", "/schema/", "/sql/")


def content_hash(content: bytes) -> str:
    return hashlib.sha256(content).hexdigest()


def classify_path(rel_path: str, *, generated: bool = False, secret_sensitive: bool = False) -> Tuple[FileClassification, str]:
    """Return (classification, source evidence) using path-based evidence."""
    lower = rel_path.lower()
    name = Path(rel_path).name.lower()
    if secret_sensitive:
        return "secret_bearing", "secret-sensitive path match"
    if generated:
        return "generated", "generated-file policy"
    if lower.endswith((".png", ".jpg", ".jpeg", ".gif", ".webp", ".ico", ".woff", ".woff2", ".ttf", ".mp4", ".mp3", ".pdf", ".zip")):
        return "asset", "binary asset extension"
    if lower.endswith((".pyc", ".pyo", ".o", ".class", ".jar", ".a", ".so", ".dylib", ".exe", ".dll")):
        return "build_output", "compiled artifact extension"
    if lower.endswith((".min.js", ".min.css", ".bundle.js", ".chunk.js")):
        return "generated", "bundler output filename"
    if name in {"package.json", "requirements.txt", "pyproject.toml", "Cargo.toml", "go.mod",
                "package-lock.json", "pnpm-lock.yaml", "yarn.lock", "Gemfile", "composer.json",
                "Pipfile", "pubspec.yaml", "Podfile", "*.csproj"} or name.endswith(".csproj"):
        return ("lockfile" if lower.endswith(("lock", "lock.json", "lock.yaml")) else "package_manifest"), "manifest filename"
    if lower in {".gitignore", ".gitattributes", ".editorconfig", ".npmrc", ".prettierrc", "tsconfig.json",
                 "eslint.config.js", ".eslintrc", ".prettierrc.json", ".github"} or lower.endswith(
        (".github/workflows",)
    ):
        return "configuration", "configuration filename"
    if lower.endswith((".env", ".env.local", ".env.production")) or name.startswith(".env"):
        return "secret_bearing", "environment file"
    if lower.startswith(("dockerfile",)) or lower in {"docker-compose.yml", "docker-compose.yaml"} or lower.endswith(".dockerfile"):
        return "infrastructure", "docker manifest"
    if lower.startswith((".github/workflows", "azure-pipelines", ".gitlab-ci")) or lower.endswith((".yml", ".yaml")) and ".github" in lower:
        return "workflow", "CI workflow path"
    if lower.endswith(".tf") or lower.endswith(".tfvars"):
        return "infrastructure", "terraform source"
    if lower.endswith((".sh", ".bash", ".zsh", ".ps1", ".bat", ".cmd")):
        return "script", "shell script extension"
    if lower.endswith((".sql",)):
        if any(marker in lower for marker in ("/migrations/", "/migration/")):
            return "migration", "migration path"
        return "schema", "sql schema/query file"
    if lower.endswith((".md", ".markdown", ".rst", ".txt")) or name in {"readme", "readme.md", "license", "changelog", "contributing"} or name.startswith("changelog"):
        if any(marker in lower for marker in ("/docs/", "/doc/")) or name.startswith("readme") or lower.endswith(".adoc"):
            return "documentation", "documentation path"
        return "documentation", "documentation filename"
    if name in {"adr.md"} or re.search(r"/adr/", lower) or re.search(r"/decisions/", lower):
        return "documentation", "architectural decision record path"
    if lower.endswith((".json", ".yaml", ".yml", ".toml", ".ini", ".cfg", ".conf", ".xml", ".plist")):
        return "configuration", "configuration extension"
    if lower.endswith((".html", ".htm", ".xhtml")):
        return "route", "html route source"
    if lower.endswith((".css", ".scss", ".sass", ".less")):
        return "style", "style extension"
    if lower.endswith((".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs", ".py", ".rs", ".go", ".swift", ".java", ".kt", ".c", ".cpp", ".h", ".hpp", ".rb", ".php", ".cs")):
        if any(marker in lower for marker in TEST_PATH_HINTS) or name.startswith("test_") or name.endswith("_test.py") or name.endswith(".test.ts") or name.endswith(".test.tsx") or name.endswith(".spec.ts") or name.endswith("_test.go") or name.endswith("Tests.swift"):
            return "test", "test path or filename convention"
        if "migrations" in lower or "migration" in lower:
            return "migration", "migration path"
        if lower.endswith((".svg",)):
            return "asset", "vector asset"
        return "source", "source extension"
    if lower.endswith((".svg",)):
        return "asset", "vector asset"
    if lower.endswith((".d.ts",)):
        return "source", "type declaration source"
    return "unknown", "no classification evidence"


def classify_content(content: str) -> Tuple[Optional[FileClassification], Optional[str]]:
    """Return (classification, source) from content hints, if any."""
    lowered = content[:4000].lower()
    if any(hint in lowered for hint in GENERATED_HINTS):
        return "generated", "generated-file content hint"
    return None, None


class InventoryService:
    def __init__(
        self,
        root_provider: Callable[[str], Path],
        connection_factory: Callable,
    ) -> None:
        self._root_provider = root_provider
        self._connection_factory = connection_factory

    def prepare(self) -> None:
        with self._connection_factory() as connection:
            connection.executescript(
                """
                CREATE TABLE IF NOT EXISTS intelligence_files (
                    file_id TEXT PRIMARY KEY,
                    project_id TEXT NOT NULL,
                    rel_path TEXT NOT NULL,
                    file_name TEXT NOT NULL,
                    extension TEXT NOT NULL DEFAULT '',
                    language TEXT,
                    binary INTEGER NOT NULL DEFAULT 0,
                    size INTEGER NOT NULL DEFAULT 0,
                    modified_at TEXT,
                    content_hash TEXT NOT NULL,
                    classification TEXT NOT NULL DEFAULT 'unknown',
                    classification_confidence TEXT NOT NULL DEFAULT 'uncertain',
                    tracked INTEGER NOT NULL DEFAULT 1,
                    ignored INTEGER NOT NULL DEFAULT 0,
                    hidden INTEGER NOT NULL DEFAULT 0,
                    generated INTEGER NOT NULL DEFAULT 0,
                    secret_sensitive INTEGER NOT NULL DEFAULT 0,
                    git_state TEXT NOT NULL DEFAULT 'clean',
                    parser TEXT,
                    parser_available INTEGER NOT NULL DEFAULT 0,
                    symbol_count INTEGER NOT NULL DEFAULT 0,
                    reference_count INTEGER NOT NULL DEFAULT 0,
                    last_indexed_at TEXT,
                    stale INTEGER NOT NULL DEFAULT 0,
                    UNIQUE(project_id, rel_path)
                );
                CREATE INDEX IF NOT EXISTS idx_intel_files_project ON intelligence_files(project_id);
                CREATE INDEX IF NOT EXISTS idx_intel_files_hash ON intelligence_files(project_id, content_hash);
                """
            )

    def scan(self, project_id: str, root: Path, *, include_hidden: bool = False) -> Tuple[FileInventoryRecord, ...]:
        """Scan the tree and upsert inventory records; returns the full current inventory."""
        current_hash: Dict[str, str] = {}
        records: List[FileInventoryRecord] = []
        try:
            files = sorted(root.rglob("*"))
        except OSError:
            files = []
        excluded = 0
        for path in files:
            rel = str(path.relative_to(root))
            parts = rel.split("/")
            if any(part in {".git", "node_modules", ".venv", "venv", "dist", "build", "__pycache__", ".next", ".turbo", ".cache", ".svn", ".hg", ".pytest_cache", ".mypy_cache", ".ruff_cache", ".coverage"} for part in parts):
                excluded += 1
                continue
            if not path.is_file():
                continue
            hidden = path.name.startswith(".")
            if hidden and not include_hidden and path.name not in {".gitignore", ".gitattributes", ".env.example", ".env", ".env.local", ".env.production", ".env.staging", ".prettierrc", ".editorconfig", ".eslintrc", ".eslintrc.json", ".eslintrc.js", ".eslintrc.cjs", ".eslintrc.yaml", ".eslintrc.yml", ".npmrc", ".dockerignore", ".nvmrc"}:
                excluded += 1
                continue
            try:
                stat = path.stat()
                size = stat.st_size
                modified_at = _iso_from_epoch(stat.st_mtime)
            except OSError:
                continue
            binary = _is_binary(path)
            content_bytes = b"" if binary else _read_head(path, 2_000_000)
            digest = content_hash(content_bytes)
            current_hash[rel] = digest
            language = _language_for(path.name)
            generated, secret = _policy_flags(rel, content_bytes, size)
            classification, evidence = classify_path(rel, generated=generated, secret_sensitive=secret)
            confidence = "reported" if classification != "unknown" else "uncertain"
            file_id = _stable_id(project_id, rel)
            records.append(
                FileInventoryRecord(
                    file_id=file_id,
                    project_id=project_id,
                    rel_path=rel,
                    file_name=path.name,
                    extension=path.suffix.lower(),
                    language=language,
                    binary=binary,
                    size=size,
                    modified_at=modified_at,
                    content_hash=digest,
                    classification=classification,
                    classification_confidence=confidence,
                    tracked=_is_tracked(project_id, rel),
                    hidden=hidden,
                    generated=generated,
                    secret_sensitive=secret,
                    parser=language if language in _PARSER_LANGUAGES else None,
                    parser_available=language in _PARSER_LANGUAGES,
                )
            )
        self._upsert_records(project_id, records)
        self._remove_missing(project_id, current_hash)
        return tuple(self.load(project_id))

    def load(self, project_id: str) -> Tuple[FileInventoryRecord, ...]:
        with self._connection_factory() as connection:
            rows = connection.execute(
                "SELECT * FROM intelligence_files WHERE project_id = ? ORDER BY rel_path",
                (project_id,),
            ).fetchall()
        return tuple(_record_from_row(row) for row in rows)

    def get(self, project_id: str, rel_path: str) -> Optional[FileInventoryRecord]:
        with self._connection_factory() as connection:
            row = connection.execute(
                "SELECT * FROM intelligence_files WHERE project_id = ? AND rel_path = ?",
                (project_id, rel_path),
            ).fetchone()
        return _record_from_row(row) if row is not None else None

    def update_symbol_counts(self, project_id: str, rel_path: str, symbols: int, references: int, parser: Optional[str]) -> None:
        with self._connection_factory() as connection:
            connection.execute(
                """
                UPDATE intelligence_files
                SET symbol_count = ?, reference_count = ?, parser = ?,
                    parser_available = CASE WHEN ? IS NULL THEN parser_available ELSE 1 END,
                    last_indexed_at = ?, stale = 0
                WHERE project_id = ? AND rel_path = ?
                """,
                (symbols, references, parser, parser, _now(), project_id, rel_path),
            )

    def mark_stale(self, project_id: str, rel_path: Optional[str] = None) -> int:
        with self._connection_factory() as connection:
            if rel_path is None:
                cursor = connection.execute(
                    "UPDATE intelligence_files SET stale = 1 WHERE project_id = ?",
                    (project_id,),
                )
            else:
                cursor = connection.execute(
                    "UPDATE intelligence_files SET stale = 1 WHERE project_id = ? AND rel_path = ?",
                    (project_id, rel_path),
                )
        return cursor.rowcount

    def _upsert_records(self, project_id: str, records: List[FileInventoryRecord]) -> None:
        with self._connection_factory() as connection:
            for record in records:
                connection.execute(
                    """
                    INSERT INTO intelligence_files (
                        file_id, project_id, rel_path, file_name, extension, language,
                        binary, size, modified_at, content_hash, classification,
                        classification_confidence, tracked, ignored, hidden, generated,
                        secret_sensitive, git_state, parser, parser_available,
                        symbol_count, reference_count, last_indexed_at, stale
                    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    ON CONFLICT(project_id, rel_path) DO UPDATE SET
                        file_id = excluded.file_id,
                        file_name = excluded.file_name,
                        extension = excluded.extension,
                        language = excluded.language,
                        binary = excluded.binary,
                        size = excluded.size,
                        modified_at = excluded.modified_at,
                        content_hash = excluded.content_hash,
                        classification = excluded.classification,
                        classification_confidence = excluded.classification_confidence,
                        hidden = excluded.hidden,
                        generated = excluded.generated,
                        secret_sensitive = excluded.secret_sensitive,
                        stale = CASE WHEN intelligence_files.content_hash != excluded.content_hash THEN 1 ELSE intelligence_files.stale END
                    """,
                    (
                        record.file_id, project_id, record.rel_path, record.file_name, record.extension,
                        record.language, int(record.binary), record.size, record.modified_at,
                        record.content_hash, record.classification, record.classification_confidence,
                        int(record.tracked), int(record.ignored), int(record.hidden), int(record.generated),
                        int(record.secret_sensitive), record.git_state, record.parser,
                        int(record.parser_available), record.symbol_count, record.reference_count,
                        record.last_indexed_at, int(record.stale),
                    ),
                )

    def _remove_missing(self, project_id: str, present: Dict[str, str]) -> None:
        with self._connection_factory() as connection:
            rows = connection.execute(
                "SELECT rel_path FROM intelligence_files WHERE project_id = ?",
                (project_id,),
            ).fetchall()
            missing = [row["rel_path"] for row in rows if row["rel_path"] not in present]
            for rel in missing:
                connection.execute(
                    "DELETE FROM intelligence_files WHERE project_id = ? AND rel_path = ?",
                    (project_id, rel),
                )


_PARSER_LANGUAGES = {"python", "javascript", "typescript", "json", "yaml", "markdown", "shell", "dockerfile"}


def _is_binary(path: Path) -> bool:
    try:
        chunk = path.open("rb").read(1024)
    except OSError:
        return True
    return b"\x00" in chunk


def _read_head(path: Path, limit: int) -> bytes:
    try:
        return path.open("rb").read(limit)
    except OSError:
        return b""


def _policy_flags(rel_path: str, content: bytes, size: int) -> Tuple[bool, bool]:
    secret = any(hint in rel_path.lower() for hint in SECRET_HINTS)
    generated = any(marker in rel_path for marker in GENERATED_PATHS)
    text = content.decode("utf-8", errors="replace") if content else ""
    # Content hints apply only to the header comment region (first 4 lines),
    # where generated-file markers such as "do not edit" live. Scanning the
    # whole file would false-positive on source that merely references the
    # term "generated", and bare substring matches pick up unrelated language
    # keywords (e.g. SQL "generated by default as identity"). Each hint is
    # therefore matched at the start of a (comment-prefixed) line.
    _COMMENT_PREFIXES = ("//", "/*", "*", "#", ";", "--", "<!--", "%")
    for line in text.splitlines()[:4]:
        stripped = line.strip().lower()
        if not stripped:
            continue
        for prefix in _COMMENT_PREFIXES:
            if stripped.startswith(prefix):
                stripped = stripped[len(prefix):].lstrip()
                break
        if any(stripped.startswith(hint) for hint in GENERATED_HINTS):
            generated = True
            break
    return generated, secret


def _is_tracked(project_id: str, rel_path: str) -> bool:
    return True


def _language_for(name: str) -> Optional[str]:
    from .detect import language_for_file

    return language_for_file(name)


def _stable_id(project_id: str, rel_path: str) -> str:
    return hashlib.sha256(("%s:%s" % (project_id, rel_path)).encode("utf-8")).hexdigest()[:24]


def _iso_from_epoch(epoch: float) -> Optional[str]:
    from datetime import datetime, timezone

    try:
        return datetime.fromtimestamp(epoch, tz=timezone.utc).isoformat()
    except (OverflowError, OSError, ValueError):
        return None


def _now() -> str:
    from datetime import datetime, timezone

    return datetime.now(timezone.utc).isoformat()


def _record_from_row(row) -> FileInventoryRecord:
    return FileInventoryRecord(
        file_id=row["file_id"],
        project_id=row["project_id"],
        rel_path=row["rel_path"],
        file_name=row["file_name"],
        extension=row["extension"],
        language=row["language"],
        binary=bool(row["binary"]),
        size=row["size"],
        modified_at=row["modified_at"],
        content_hash=row["content_hash"],
        classification=row["classification"],
        classification_confidence=row["classification_confidence"],
        tracked=bool(row["tracked"]),
        ignored=bool(row["ignored"]),
        hidden=bool(row["hidden"]),
        generated=bool(row["generated"]),
        secret_sensitive=bool(row["secret_sensitive"]),
        git_state=row["git_state"],
        parser=row["parser"],
        parser_available=bool(row["parser_available"]),
        symbol_count=row["symbol_count"],
        reference_count=row["reference_count"],
        last_indexed_at=row["last_indexed_at"],
        stale=bool(row["stale"]),
    )
