create table if not exists public.system_metrics (
  id bigint generated by default as identity primary key,
  recorded_at timestamptz not null default now(),
  cpu_percent numeric(5, 2) not null check (cpu_percent between 0 and 100),
  ram_percent numeric(5, 2) not null check (ram_percent between 0 and 100),
  disk_percent numeric(5, 2) not null check (disk_percent between 0 and 100),
  uptime_seconds bigint not null default 0 check (uptime_seconds >= 0),
  cpu_detail text,
  ram_detail text,
  disk_detail text
);

create index if not exists system_metrics_recorded_at_idx
  on public.system_metrics (recorded_at desc);

create table if not exists public.bots (
  id text primary key,
  name text not null,
  role text not null,
  description text not null default '',
  status text not null default 'stopped' check (status in ('running', 'stopped')),
  tasks_completed bigint not null default 0 check (tasks_completed >= 0),
  queued_tasks integer not null default 0 check (queued_tasks >= 0),
  success_rate numeric(5, 2) not null default 100 check (success_rate between 0 and 100),
  activity text not null default 'No recent activity',
  icon text not null default 'fa-robot',
  updated_at timestamptz not null default now()
);

alter table public.system_metrics enable row level security;
alter table public.bots enable row level security;

revoke all on table public.system_metrics from anon, authenticated;
revoke all on table public.bots from anon, authenticated;
grant select on table public.system_metrics to anon, authenticated;
grant select, insert, update, delete on table public.system_metrics to service_role;
grant select, insert, update, delete on table public.bots to service_role;

drop policy if exists "Public read-only metrics" on public.system_metrics;
create policy "Public read-only metrics"
  on public.system_metrics
  for select
  to anon, authenticated
  using (true);

comment on table public.system_metrics is
  'Read-only public telemetry sampled by JoeOS; writes are server-side only.';
comment on table public.bots is
  'JoeOS bot fleet state; access is restricted to the trusted backend.';
